chore(perf): using runtime callers to improve the performance of leak detection
dgraph-io/ristretto pull request #255
Opened 2021-02-25 18:54 UTC by aman-bansal

2021-02-25 21:15 UTC, manishrjain commented
Not sure if this is going to be much faster than what we're doing today.

2021-03-08 06:32 UTC, ahsanbarkati reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/255)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @aman-bansal, @jarifibrahim, @manishrjain, and @martinmr)

___
*[z/out.txt, line 0 at r2](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVFXHdc884mJZr6clwu:-MVFXHdc884mJZr6clwv:b3dmgsh) ([raw file](https://github.com/dgraph-io/ristretto/blob/12d7dcf7c83835af5947f2b40ebaeef3945a17d9/z/out.txt#L0)):*
Why do we have this file? 


<!-- Sent from Reviewable.io -->

2021-03-08 06:48 UTC, anurags92 commented
Shouldn't we run some numbers if the perf actually improves? Or is it in some accompanying PR?

2021-03-08 10:58 UTC, jarifibrahim requested changes
Got some comments.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/255#-:-MVGU8LBAoVu1fNCLgxU:b17ku4n)* status: 0 of 11 files reviewed, 8 unresolved discussions (waiting on @aman-bansal, @manishrjain, and @martinmr)

___
*[z/allocator.go, line 69 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGRy1sDdcNAp24lMkp:-MVGRy1sDdcNAp24lMkq:bbn7jvs) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/allocator.go#L69)):*
> ```Go
> 
> // NewAllocator creates an allocator starting with the given size.
> func NewAllocator(sz int, tag string) *Allocator {
> ```

a.Tag is already exposed. We'll need to fix all occurrences of  `NewAllocator` if you make this change.
___
*[z/allocator.go, line 328 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGS0vm5vJpJRFBLuxu:-MVGS0vm5vJpJRFBLuxv:b-ugtco6) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/allocator.go#L328)):*
> ```Go
> }
> 
> func (p *AllocatorPool) Get(sz int, tag string) *Allocator {
> ```

Don't need this. `a.Tag` is already exposed.
___
*[z/buffer.go, line 76 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGTYzo4CorN0Gs5rnj:-MVGTYzo4CorN0Gs5rnk:b-9jzb8r) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/buffer.go#L76)):*
> ```Go
> 
> // NewBuffer is a helper utility, which creates a virtually unlimited Buffer in UseCalloc mode.
> func NewBuffer(sz int, tag string) *Buffer {
> ```

If you just expose `buffer.Tag` you won't need this change and the rest of the changes in this file.
___
*[z/calloc_jemalloc.go, line 56 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGTx9i7OxDiMQ_9HcF:-MVGTx9i7OxDiMQ_9HcG:b-h8icrh) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/calloc_jemalloc.go#L56)):*
> ```Go
> }
> 
> func Calloc(n int, tag string) []byte {
> ```

I would've put `tag` before the size but that's a personal preference.
___
*[z/calloc_jemalloc.go, line 82 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGSziX1s2lf9-alZIq:-MVGSziX1s2lf9-alZIr:b-dsaw60) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/calloc_jemalloc.go#L82)):*
> ```Go
> 
> 	uptr := unsafe.Pointer(ptr)
> 	if dallocs != nil {
> ```

Remove this if
___
*[z/calloc_jemalloc.go, line 83 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGT1JzAPsNVgKRTqPR:-MVGT1JzAPsNVgKRTqPS:b-kxu7v0) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/calloc_jemalloc.go#L83)):*
> ```Go
> 	uptr := unsafe.Pointer(ptr)
> 	if dallocs != nil {
> 		// If leak detection is enabled.
> ```

Remove this comment
___
*[z/calloc_jemalloc.go, line 109 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGTC76ByIMgzuAFEF6:-MVGTC76ByIMgzuAFEF7:b-dsaw60) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/calloc_jemalloc.go#L109)):*
> ```Go
> 		atomic.AddInt64(&numBytes, -int64(sz))
> 
> 		if dallocs != nil {
> ```

Remove this if


<!-- Sent from Reviewable.io -->

2021-03-08 12:19 UTC, aman-bansal reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/255)* status: 0 of 11 files reviewed, 8 unresolved discussions (waiting on @ahsanbarkati, @aman-bansal, @jarifibrahim, @manishrjain, and @martinmr)

___
*[z/allocator.go, line 69 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGRy1sDdcNAp24lMkp:-MVGktQs3Q7zYGKSajid:b8zym7h) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/allocator.go#L69)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

a.Tag is already exposed. We'll need to fix all occurrences of  `NewAllocator` if you make this change.
</blockquote></details>

The idea is if we make this part of allocator function than this will ensure that all new allocators will have tags. this is to make necessary that all tags have tags
___
*[z/buffer.go, line 76 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGTYzo4CorN0Gs5rnj:-MVGlMnO0VRnPrgULOus:b-oeo5z9) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/buffer.go#L76)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

If you just expose `buffer.Tag` you won't need this change and the rest of the changes in this file.
</blockquote></details>

But in future use, it might happen that not all buffers will have tags. this is to make tags necessary
___
*[z/calloc_jemalloc.go, line 56 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGTx9i7OxDiMQ_9HcF:-MVGlWY47-ao54CxSujL:bcp4eeq) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/calloc_jemalloc.go#L56)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

I would've put `tag` before the size but that's a personal preference.
</blockquote></details>

size seems imp. thats why :sweat_smile: 
___
*[z/calloc_jemalloc.go, line 82 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGSziX1s2lf9-alZIq:-MVGlbKy63R_5yd5C15m:b-896fix) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/calloc_jemalloc.go#L82)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Remove this if
</blockquote></details>

Done.
___
*[z/calloc_jemalloc.go, line 83 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGT1JzAPsNVgKRTqPR:-MVGlbbsAgDY04lVymKn:b-896fix) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/calloc_jemalloc.go#L83)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Remove this comment
</blockquote></details>

Done.
___
*[z/calloc_jemalloc.go, line 109 at r3](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVGTC76ByIMgzuAFEF6:-MVGlc8HABBjrMZ0fG4d:b-896fix) ([raw file](https://github.com/dgraph-io/ristretto/blob/a5cf2b1e884eb8a21f0cca5210aa011d8744af62/z/calloc_jemalloc.go#L109)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Remove this if
</blockquote></details>

Done.
___
*[z/out.txt, line  at r2](https://reviewable.io/reviews/dgraph-io/ristretto/255#-MVFXHdc884mJZr6clwu:-MVGld2v69rQ0qKHegah:btzsfrm) ([raw file](https://github.com/dgraph-io/ristretto/blob/12d7dcf7c83835af5947f2b40ebaeef3945a17d9/z/out.txt#L)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

Why do we have this file? 
</blockquote></details>

missed it. deleted now


<!-- Sent from Reviewable.io -->

2021-03-08 13:41 UTC, jarifibrahim approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/ristretto/255#-:-MVH3bYZ8un8LgHEdRNV:bnfp4nl)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @ahsanbarkati, @aman-bansal, @jarifibrahim, @manishrjain, and @martinmr)



<!-- Sent from Reviewable.io -->

2021-03-09 07:31 UTC, merged