make policy an interface
dgraph-io/ristretto pull request #295
Opened 2022-05-26 10:32 UTC by tushar-zomato

add option to always admit new items

2022-05-26 10:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/ristretto?pullRequest=295) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/ristretto?pullRequest=295) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/ristretto?pullRequest=295) it.</sub>

2022-06-01 21:54 UTC, joshua-goldstein commented
There is the option of setting `MaxCost` and `NumCounters` to be very large values, so that the cache will admit essentially all items (except those dropped in the buffers).  You might also be able to add items with the cost of each item to be 0.  These are much easier solutions than adding an entirely new policy.

2022-06-01 21:54 UTC, joshua-goldstein commented
There is the option of setting `MaxCost` and `NumCounters` to be very large values, so that the cache will admit essentially all items (except those dropped in the buffers).  You might also be able to add items with the cost of each item to be 0.  These are much easier solutions than adding an entirely new policy.

2023-07-02 06:38 UTC, MichelDiz requested changes

2023-07-02 06:38 UTC, MichelDiz commented on .deepsource.toml
> +  import_path = 'github.com/tushar-zomato/ristretto'
Why this renaming?

2024-07-26 02:16 UTC, closed without merging