docs: format example on readme
dgraph-io/ristretto pull request #339
Opened 2023-04-26 04:02 UTC by rfyiamcool

## what

format code example on readme.md.

2023-05-14 23:53 UTC, mangalaman93 requested changes
Just one comment, this PR is good to go.

2023-05-14 23:53 UTC, mangalaman93 commented on README.md
> +	"fmt"
we should leave a new line in between

2023-05-15 02:35 UTC, rfyiamcool commented on README.md
> +	"fmt"
done 😁

2023-05-16 11:35 UTC, mangalaman93 approved these changes

2023-05-16 11:36 UTC, merged